# Generated by Django 3.2.3 on 2021-06-19 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='song',
            name='art_work',
            field=models.ImageField(upload_to='art_works'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vibes.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to='music'),
        ),
    ]
