# Generated by Django 3.2.3 on 2021-06-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0003_alter_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='art_work',
        ),
    ]
